name: Create Release
on:
  push:
    branches:
      - 'canary'
  pull_request:
    types:
      - labeled
      - synchronize

concurrency:
  group: ${{ github.head_ref }} || concat(${{ github.ref }}, ${{ github.workflow }})
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      upload-artifacts: true
    if: |
      github.repository == 'wolono/azerothcore'
      && !github.event.pull_request.draft
      && (github.ref == 'refs/heads/canary' || contains(github.event.pull_request.labels.*.name, 'run-build') || github.event.label.name == 'run-build')

  release:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: bin/
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: bin/**/*
          name: Automated Release v${{ github.sha.substring(0, 8) }}
          tag_name: v${{ github.sha.substring(0, 8) }}
